//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryFarmManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BroilerBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BroilerBatch()
        {
            this.BroilerBatchDatas = new HashSet<BroilerBatchData>();
        }
    
        public int bb_id { get; set; }
        public string bb_name { get; set; }
        public string bb_arrivaldate { get; set; }
        public Nullable<int> bb_totalqty { get; set; }
        public Nullable<int> bb_totalcost { get; set; }
        public Nullable<int> pltry_id { get; set; }
        public Nullable<int> worker_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BroilerBatchData> BroilerBatchDatas { get; set; }
        public virtual Poultry Poultry { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
