//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryFarmManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayerBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LayerBatch()
        {
            this.LayerBatchDatas = new HashSet<LayerBatchData>();
        }
    
        public int lb_id { get; set; }
        public string lb_name { get; set; }
        public string lb_arrivaldate { get; set; }
        public Nullable<int> lb_totalqty { get; set; }
        public Nullable<int> lb_totalcost { get; set; }
        public Nullable<int> pltry_id { get; set; }
        public Nullable<int> worker_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LayerBatchData> LayerBatchDatas { get; set; }
        public virtual Poultry Poultry { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
