//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryFarmManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayerBatchData
    {
        public int lbd_id { get; set; }
        public string feed_type { get; set; }
        public Nullable<int> costoffeedinkg { get; set; }
        public string vaccine_name { get; set; }
        public Nullable<int> totalvaccine_cost { get; set; }
        public Nullable<int> totalfeedconsumedinkg { get; set; }
        public Nullable<int> eggs_produced { get; set; }
        public Nullable<int> ageindays { get; set; }
        public Nullable<int> pltry_id { get; set; }
        public Nullable<int> mortality { get; set; }
        public Nullable<int> lb_id { get; set; }
        public Nullable<int> sale_status { get; set; }
    
        public virtual LayerBatch LayerBatch { get; set; }
        public virtual Poultry Poultry { get; set; }
    }
}
