//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryFarmManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoultryFarmManagementSystemEntities10 : DbContext
    {
        public PoultryFarmManagementSystemEntities10()
            : base("name=PoultryFarmManagementSystemEntities10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BroilerBatch> BroilerBatches { get; set; }
        public virtual DbSet<BroilerBatchData> BroilerBatchDatas { get; set; }
        public virtual DbSet<LayerBatch> LayerBatches { get; set; }
        public virtual DbSet<LayerBatchData> LayerBatchDatas { get; set; }
        public virtual DbSet<Poultry> Poultries { get; set; }
        public virtual DbSet<Poultrire> Poultrires { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
    }
}
